- name: Install unzip
  package:
    name: unzip

- name: Install terraform
  unarchive:
    src: http://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
