---

- hosts: rpi
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: purge emacs package
    apt:
      name: emacs
      state: absent

  - name: purge vlc package
    apt:
      name: vlc
      state: absent
